"""Add application follow ups

Revision ID: 0ab4cb452da1
Revises: e5d8ff2c2762
Create Date: 2026-09-21 13:24:17.011003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab4cb452da1'
down_revision: Union[str, Sequence[str], None] = 'e5d8ff2c2762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_ups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_application_id'), 'follow_ups', ['application_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_scheduled_at'), 'follow_ups', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_ups_scheduled_at'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_application_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    # ### end Alembic commands ###
