"""Add resume metadata

Revision ID: 2072b1c241d4
Revises: 0ab4cb452da1
Create Date: 2026-09-21 15:03:51.853651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2072b1c241d4'
down_revision: Union[str, Sequence[str], None] = '0ab4cb452da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "resumes",
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.add_column(
        "resumes",
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE resumes SET uploaded_at = CURRENT_TIMESTAMP "
        "WHERE uploaded_at IS NULL"
    )

    op.execute(
        "UPDATE resumes SET is_default = FALSE "
        "WHERE is_default IS NULL"
    )

    op.alter_column(
        "resumes",
        "uploaded_at",
        existing_type=sa.DateTime(),
        nullable=False,
    )

    op.alter_column(
        "resumes",
        "is_default",
        existing_type=sa.Boolean(),
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_default')
    op.drop_column('resumes', 'uploaded_at')
    # ### end Alembic commands ###
