"""add jd hash to resume matches

Revision ID: 9d3df68edb77
Revises: d2af560a5a07
Create Date: 2026-08-13 11:54:00.381198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3df68edb77'
down_revision: Union[str, Sequence[str], None] = 'd2af560a5a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add the column temporarily as nullable
    op.add_column(
        "resume_matches",
        sa.Column(
            "jd_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    # Existing records need a value.
    # We will calculate real hashes for newly created analyses.
    # Use a temporary placeholder for existing records.
    op.execute(
        "UPDATE resume_matches "
        "SET jd_hash = 'legacy'"
        " WHERE jd_hash IS NULL"
    )

    # Now make the column required
    op.alter_column(
        "resume_matches",
        "jd_hash",
        existing_type=sa.String(length=64),
        nullable=False,
    )

    # Add the index
    op.create_index(
        op.f("ix_resume_matches_jd_hash"),
        "resume_matches",
        ["jd_hash"],
        unique=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_matches_jd_hash'), table_name='resume_matches')
    op.drop_column('resume_matches', 'jd_hash')
    # ### end Alembic commands ###
