"""add application priority

Revision ID: e5d8ff2c2762
Revises: 9d3df68edb77
Create Date: 2026-08-14 09:48:52.835287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d8ff2c2762'
down_revision: Union[str, Sequence[str], None] = '9d3df68edb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "applications",
        sa.Column(
            "priority",
            sa.String(length=20),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE applications SET priority = 'medium' "
        "WHERE priority IS NULL"
    )

    op.alter_column(
        "applications",
        "priority",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'priority')
    # ### end Alembic commands ###
